version: '2'

services:
  pgsql:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: secret
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - 53432:5432
    restart: always

  redis:
    image: redis:5.0-alpine
    volumes:
      - ./redis-data:/data
    ports:
      - 53379:6379
    restart: always

