on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_docker_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to registry
        uses: actions/docker/login@master
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_USERNAME: jokester
          DOCKER_PASSWORD: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: v0.4.1
          qemu-version: 4.2.0-7

      - name: Echo Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64    \
            --output "type=image,push=true"       \
            --file ./backend/Dockerfile ./backend \
            --tag docker.pkg.github.com/jokester/momocraft/backend:latest

