name: Check (backend)

on:
  pull_request:
    paths:
    - backend/**

defaults:
  run:
    shell: bash
    working-directory: backend

jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - uses: bahmutov/npm-install@v1
      with:
        working-directory: backend

    - name: Type Check
      run: yarn typecheck

    - name: Lint
      run: yarn lint
