name: Check (frontend)

on:
  pull_request:
    paths:
    - frontend/**
    - backend/**

defaults:
  run:
    shell: bash
    working-directory: frontend

jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v2

    - uses: bahmutov/npm-install@v1
      with:
        working-directory: frontend

    - name: Type Check
      run: yarn typecheck

    - name: Lint
      run: yarn lint

    - name: Test
      run: yarn test --ci

    - name: Create Prod Build
      run: yarn analyze

    - name: Archive Bundle Analyze Report
      uses: actions/upload-artifact@v2
      with:
        name: webpack-bundle-analyzer-report
        path: .next/**/report.html
